"""Global nodes for ComfyUI."""

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .image_preview import (
    NODE_CLASS_MAPPINGS as IMAGE_PREVIEW_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PREVIEW_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS,
    **IMAGE_PREVIEW_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_PREVIEW_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
