"""
ComfyUI Simple Utility Nodes

A collection of simple utility nodes for ComfyUI including time-related,
string manipulation, switch, script, and global variable nodes.
"""

from .time_nodes import NODE_CLASS_MAPPINGS as TIME_NODE_CLASS_MAPPINGS
from .time_nodes import NODE_DISPLAY_NAME_MAPPINGS as TIME_NODE_DISPLAY_NAME_MAPPINGS
from .string_nodes import NODE_CLASS_MAPPINGS as STRING_NODE_CLASS_MAPPINGS
from .string_nodes import NODE_DISPLAY_NAME_MAPPINGS as STRING_NODE_DISPLAY_NAME_MAPPINGS
from .switch_nodes import NODE_CLASS_MAPPINGS as SWITCH_NODE_CLASS_MAPPINGS
from .switch_nodes import NODE_DISPLAY_NAME_MAPPINGS as SWITCH_NODE_DISPLAY_NAME_MAPPINGS
from .script_nodes import NODE_CLASS_MAPPINGS as SCRIPT_NODE_CLASS_MAPPINGS
from .script_nodes import NODE_DISPLAY_NAME_MAPPINGS as SCRIPT_NODE_DISPLAY_NAME_MAPPINGS
from .global_variable_nodes import NODE_CLASS_MAPPINGS as GLOBAL_VAR_NODE_CLASS_MAPPINGS
from .global_variable_nodes import NODE_DISPLAY_NAME_MAPPINGS as GLOBAL_VAR_NODE_DISPLAY_NAME_MAPPINGS

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **TIME_NODE_CLASS_MAPPINGS,
    **STRING_NODE_CLASS_MAPPINGS,
    **SWITCH_NODE_CLASS_MAPPINGS,
    **SCRIPT_NODE_CLASS_MAPPINGS,
    **GLOBAL_VAR_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TIME_NODE_DISPLAY_NAME_MAPPINGS,
    **STRING_NODE_DISPLAY_NAME_MAPPINGS,
    **SWITCH_NODE_DISPLAY_NAME_MAPPINGS,
    **SCRIPT_NODE_DISPLAY_NAME_MAPPINGS,
    **GLOBAL_VAR_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
