"""VRAM Cache package – saving, loading & RAM clearing nodes."""

from .vram_cache_saving import (
    NODE_CLASS_MAPPINGS as SAVING_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVING_DISPLAY_NAME_MAPPINGS,
)
from .vram_cache_loading import (
    NODE_CLASS_MAPPINGS as LOADING_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOADING_DISPLAY_NAME_MAPPINGS,
)
from .vram_ram_cache_clearing import (
    NODE_CLASS_MAPPINGS as CLEARING_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CLEARING_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **SAVING_CLASS_MAPPINGS,
    **LOADING_CLASS_MAPPINGS,
    **CLEARING_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SAVING_DISPLAY_NAME_MAPPINGS,
    **LOADING_DISPLAY_NAME_MAPPINGS,
    **CLEARING_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
